aliases: # ProductID (Found under 'Settings'->'Equipment' on www.picobrew.com) mapping to friendly nickname
  Zymatic:
    #ProductID : Nickname
  PicoBrew:
    #ProductID : Nickname
  PicoFerm:
    #ProductID : Nickname
